[build]
  base = ""
  publish = "web-app/build"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Disable secrets scanning for expected public frontend environment variables
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_URL,REACT_APP_SUPABASE_ANON_KEY,REACT_APP_API_BASE_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"